### ISSUE TITLE
Cannot start up docker-compose

### ISSUE THREAD

**Issue by nathanloyer** [vrudikov/typescript-rest-boilerplate#13]
I just tried checking out master and starting this project up using the commands in the readme. 

```
npm install
./build.sh
docker-compose up
```

And I got an error from the api server:

```typescript-rest-boilerplate_1  | Error starting server: Unexpected token export```

I didn't make any local modifications or anything so I'm not sure why it wouldn't work. I'm on a mac with macos v10.12.6, npm v5.10.0, node v8.12.0, docker-compose v1.23.2, docker v18.09.2.

Is this something in my environment that is messed up? I can give more information if needed.

**Comment by vrudikov** [comment]
Let me check

**Comment by vrudikov** [comment]
yep. reproduced. want to try to fix it today-tomorrow

**Comment by marekkrivan** [comment]
Hi, I have the same problem. Yesterday I downloaded this boilerplate a can not start the server via docker. When will be fixed this problem?

**Comment by vrudikov** [comment]
Fix in progress

**Comment by vrudikov** [comment]
The issue is fixed. Please check updated readme
